### ISSUE TITLE
nproc usage

### ISSUE THREAD

**Issue by micwoj92** [samarthj/AUR#1]
You're not supposed to use that as some people do not want to run with all their cores.
https://github.com/samarthj/AUR/blob/fa402a1de46fa2bda520805793781f992bfed6e3/pyinstaller/PKGBUILD#L47
Also I don't know why you are rewritting  PKGBUILDs in that weird way but I guess that's just your preference.

**Comment by samarthj** [comment]
point taken for `nproc` use. I shall update that.

I am not certain what you mean by "rewriting in a weird way". Would you please elaborate on that?

**Comment by micwoj92** [comment]
Maybe not weird, but rather uncommon and discouraged.
Example is this commit https://aur.archlinux.org/cgit/aur.git/commit/?h=pyexiftool&id=4a1c043199217604ef5e860cbea27c26e6c5f823

Looking at the [Python packaging guidelines](https://wiki.archlinux.org/title/Python_package_guidelines#pip) 
"Warning: Use of pip and/or wheel packages is discouraged in favor of setuptools source packages, and should only be used when the latter is not a viable option (for example, packages which only come with wheel sources, and therefore cannot be installed using setuptools)."

**Comment by samarthj** [comment]
aah...  I see.

I do it this way for a few reasons:

- for many packages that reduces the complexity of make the dependency trees
- I have several packages that I maintain that use pypi releases and wanted to standardize their installs. whl installs are straightforward, setup installs are sometimes finicky
- it is easier to automate seamless version updates directly from pypi whl releases that don't break as opposed to going with the setuptools route. 
- install times are faster when comparing whl vs src

Let me know if you are facing any troubles with using the whl install strategy in particular.

I have updated all the python packages and removed nproc. They should release automatically on the next github action scheduled run (runs every 24 hrs).

**Comment by micwoj92** [comment]
Thanks for removing nproc usage.

I don't have any problems in your packages, I just came across them because I was subcribed to one package. It's just discouraged for some reason (I don't use/maintain enough python things for it to have impact on me) so if I were you I would stick to recommended way.
Let me go over your points (as someone who doesn't use python much):

>     * for many packages that reduces the complexity of make the dependency trees

That's fair.
>     * I have several packages that I maintain that use pypi releases and wanted to standardize their installs. whl installs are straightforward, setup installs are sometimes finicky

How are setup install "sometimes" finicky? It's just `python setup.py build`. Again, I don't know much, so there is probably some rare occasion where it works that I'm not aware of.
>     * it is easier to automate seamless version updates directly from pypi whl releases that don't break as opposed to going with the setuptools route.

I don't think that's issue. I've never came across such thing (I guess worst thing could be some dependency change, but you could probably also automate that reading requirements.txt or some other file with dependencies)
>     * install times are faster when comparing whl vs src

Most python- packages are small, I don't think it really matters.


I would advise you to open discussion on Arch forum or on wiki talk page to remove that warning tag if you really think that it shouldn't be there.

**Comment by micwoj92** [comment]
Personally I like automation but in real world you will never have everything standardized ;)
https://xkcd.com/927/

**Comment by samarthj** [comment]
> How are setup install "sometimes" finicky? It's just python setup.py build. Again, I don't know much, so there is probably some rare occasion where it's different that I'm not aware of.

I meant finicky in the sense that for example some things I would need to do things before/after build for specific architectures. The problem with that is I don't really deal with multiple archs, plus the developer of the package is more well versed in the intricacies around it. If/when something doesn't work as expected, I have to be the one to figure out what went wrong there. Whereas, when there are whl pkgs that are built for specific architectures and/or any, I have more guarantees there that the developer has taken the effort to verify and release that, and I can just install their release. It just becomes more of a binary release than a source compile, making it less possible for things to go wrong. Plus that whl file is directly taken from pypi, which means it is tested by hundreds of other users in addition to the developer.

> I don't think that's issue. I've never came across such thing (I guess worst thing could be some dependency change, but you could probably also automate that reading requirements.txt or some other file with dependencies)

That is true. Python dev is in a weird place though where in some places setup.py and requirements.txt are being replaced with pyproject.toml. I see it going in that direction in the future for many more things. Some devs maintain both these days but not all of them. Newer things tend to only have the pyproject.toml treatment. And many places where only pyproject.toml is the only available resource, the wiki itself states that the workaround is gross and needs to be updated to find a non-gross way out. With that in flux, I just made it easier for myself by using their whl files instead, which is standard for pretty much everything.

> Most python- packages are small, I don't think it really matters.

Absolutely true.

I am not particularly interested in carving out a new standard. Just focusing on what I can do for the packages I care about and using one standard that I know for a fact is not going anywhere anytime soon. And it will be easy to move to whatever the standard ends up being going forward since I am doing things consistently on my end. As long as this works and doesn't cause any problems for any use-cases, I am not really worried about doing things the "right" way. :)

**Comment by micwoj92** [comment]
> I meant finicky in the sense that for example some things I would need to do things before/after build for specific architectures.

I've never came across something like this. Most of the time people on AUR would comment if they had trouble installing on some non x86_64 architecture anyway.

Thanks for your reasoning. I don't see point in talking since there isn't much more to talk about

And thanks again for quick fix, I will open new issue if I happen to use any of your packages and see some issue in future.
