### ISSUE TITLE
Build python wheels, rather than downloading prebuilt.

### ISSUE THREAD

**Issue by micwoj92** [samarthj/AUR#7]
I've raised my concerns previously in https://github.com/samarthj/AUR/issues/1#issuecomment-962539892
Now I have riscv64 board I have troubles with your package (pyinstaller in this case).
Also python packaging guidelines have changed since I wrote last issue and now mainly recommend using pep517.

**Comment by samarthj** [comment]
Thanks for re-raising the issue. My earlier attempt at getting it working was a wash due to the way the tests were done for the package, which is why it was just packaged using the release wheel. 

However, I have spent the last on it since yesterday (luckily, I am on vacation) and had some time to focus on this. There have been several changes that helped fix most of the issues I had upstream as well. So been making good headway on a new and robust build setup. I should have a new release for the `pyinstaller` suite of packages with tests in a couple of hours.

Please test it out on `riscv64`, and let me know the feedback once I push it out (I'll update the ticket when I push it out).

**Comment by samarthj** [comment]
I have finished working on this (and both the release and git versions are now stable and out). Let me know how it works out.

**Comment by micwoj92** [comment]
Works, thanks.
